version: "3.8"
name: stock-dashboard
services:
  web:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: stock-dashboard
    hostname: stock-dashboard
    ports:
      - 8501:8501
    volumes:
      - ./app:/var/www/app
